# ============================================================
#  PogClip — Web Server  (server.py)
#
#  This is the backend that powers the whole website.
#  It handles:
#    - User signup and login
#    - Dashboard data
#    - Clip management
#    - API endpoints for the desktop app
# ============================================================

from flask import Flask, render_template, request, redirect, url_for, jsonify, session
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
import os
import secrets
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ── Security settings ──
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', secrets.token_hex(32))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///pogclip.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# ── Initialize extensions ──
db          = SQLAlchemy(app)
bcrypt      = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'login'

# ============================================================
#  DATABASE MODELS
# ============================================================

class User(UserMixin, db.Model):
    """A PogClip user account."""
    id            = db.Column(db.Integer, primary_key=True)
    username      = db.Column(db.String(80), unique=True, nullable=False)
    email         = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    plan          = db.Column(db.String(20), default='free')
    created_at    = db.Column(db.DateTime, default=datetime.utcnow)

    # Connected platform accounts
    twitch_username  = db.Column(db.String(80))
    kick_username    = db.Column(db.String(80))
    tiktok_connected = db.Column(db.Boolean, default=False)
    youtube_connected= db.Column(db.Boolean, default=False)

    # Clip preferences
    clip_style       = db.Column(db.String(50), default='hype_moment')
    caption_style    = db.Column(db.String(50), default='slam')

    # API key for the desktop app to authenticate
    api_key          = db.Column(db.String(64), unique=True)

    clips = db.relationship('Clip', backref='user', lazy=True)

    def __repr__(self):
        return f'<User {self.username}>'


class Clip(db.Model):
    """A clip generated by PogClip."""
    id           = db.Column(db.Integer, primary_key=True)
    user_id      = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    clip_id      = db.Column(db.String(64), unique=True, nullable=False)
    template     = db.Column(db.String(50))
    platform     = db.Column(db.String(50))
    score        = db.Column(db.Float)
    url          = db.Column(db.String(500))
    s3_key       = db.Column(db.String(500))
    views        = db.Column(db.Integer, default=0)
    likes        = db.Column(db.Integer, default=0)
    posted       = db.Column(db.Boolean, default=False)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            'id':         self.clip_id,
            'template':   self.template,
            'platform':   self.platform,
            'score':      self.score,
            'url':        self.url,
            'views':      self.views,
            'likes':      self.likes,
            'posted':     self.posted,
            'created_at': self.created_at.isoformat(),
        }


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# ============================================================
#  ROUTES — PUBLIC PAGES
# ============================================================

@app.route('/')
def index():
    """Landing page."""
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
    return render_template('index.html')


@app.route('/signup', methods=['GET', 'POST'])
def signup():
    """Create a new account."""
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))

    if request.method == 'POST':
        username = request.form.get('username', '').strip()
        email    = request.form.get('email', '').strip().lower()
        password = request.form.get('password', '')

        # Validation
        errors = []
        if len(username) < 3:
            errors.append('Username must be at least 3 characters.')
        if '@' not in email:
            errors.append('Please enter a valid email.')
        if len(password) < 8:
            errors.append('Password must be at least 8 characters.')
        if User.query.filter_by(username=username).first():
            errors.append('Username already taken.')
        if User.query.filter_by(email=email).first():
            errors.append('Email already registered.')

        if errors:
            return render_template('signup.html', errors=errors,
                                   username=username, email=email)

        # Create user
        hashed_pw = bcrypt.generate_password_hash(password).decode('utf-8')
        api_key   = secrets.token_hex(32)
        user = User(
            username=username,
            email=email,
            password_hash=hashed_pw,
            api_key=api_key,
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)
        return redirect(url_for('onboarding'))

    return render_template('signup.html')


@app.route('/login', methods=['GET', 'POST'])
def login():
    """Log into an existing account."""
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))

    if request.method == 'POST':
        email    = request.form.get('email', '').strip().lower()
        password = request.form.get('password', '')
        remember = request.form.get('remember') == 'on'

        user = User.query.filter_by(email=email).first()

        if user and bcrypt.check_password_hash(user.password_hash, password):
            login_user(user, remember=remember)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('dashboard'))
        else:
            return render_template('login.html',
                                   error='Invalid email or password.',
                                   email=email)

    return render_template('login.html')


@app.route('/logout')
@login_required
def logout():
    """Log out."""
    logout_user()
    return redirect(url_for('index'))


# ============================================================
#  ROUTES — PROTECTED PAGES
# ============================================================

@app.route('/onboarding')
@login_required
def onboarding():
    """New user onboarding flow."""
    return render_template('onboarding.html', user=current_user)


@app.route('/dashboard')
@login_required
def dashboard():
    """Main dashboard."""
    clips = Clip.query.filter_by(user_id=current_user.id)\
                      .order_by(Clip.created_at.desc())\
                      .limit(20).all()
    return render_template('dashboard.html',
                           user=current_user,
                           clips=clips)


@app.route('/download')
@login_required
def download():
    """Download page for the desktop app."""
    return render_template('download.html',
                           user=current_user,
                           api_key=current_user.api_key)


# ============================================================
#  API ROUTES — used by the desktop app
# ============================================================

def verify_api_key(api_key):
    """Check if an API key is valid and return the user."""
    return User.query.filter_by(api_key=api_key).first()


@app.route('/api/verify', methods=['POST'])
def api_verify():
    """Desktop app calls this to verify its API key on startup."""
    data    = request.get_json()
    api_key = data.get('api_key', '')
    user    = verify_api_key(api_key)

    if not user:
        return jsonify({'success': False, 'error': 'Invalid API key'}), 401

    return jsonify({
        'success':      True,
        'username':     user.username,
        'plan':         user.plan,
        'clip_style':   user.clip_style,
        'caption_style': user.caption_style,
        'twitch':       user.twitch_username,
        'kick':         user.kick_username,
    })


@app.route('/api/clips', methods=['POST'])
def api_save_clip():
    """
    Desktop app calls this when a clip is ready.
    Saves clip info to the database so it shows in the dashboard.
    """
    data    = request.get_json()
    api_key = data.get('api_key', '')
    user    = verify_api_key(api_key)

    if not user:
        return jsonify({'success': False, 'error': 'Invalid API key'}), 401

    # Check clip limit based on plan
    if user.plan == 'free':
        today_clips = Clip.query.filter_by(user_id=user.id).filter(
            Clip.created_at >= datetime.utcnow().replace(hour=0, minute=0)
        ).count()
        if today_clips >= 3:
            return jsonify({'success': False, 'error': 'Free plan limit reached'}), 403

    clip = Clip(
        user_id  = user.id,
        clip_id  = data.get('clip_id'),
        template = data.get('template'),
        platform = data.get('platform'),
        score    = data.get('score'),
        url      = data.get('url'),
        s3_key   = data.get('s3_key'),
    )
    db.session.add(clip)
    db.session.commit()

    return jsonify({'success': True, 'clip_id': clip.clip_id})


@app.route('/api/clips/<clip_id>/post', methods=['POST'])
@login_required
def api_post_clip(clip_id):
    """Mark a clip as posted."""
    clip = Clip.query.filter_by(
        clip_id=clip_id,
        user_id=current_user.id
    ).first_or_404()

    clip.posted = True
    db.session.commit()
    return jsonify({'success': True})


@app.route('/api/clips/<clip_id>', methods=['DELETE'])
@login_required
def api_delete_clip(clip_id):
    """Delete a clip."""
    clip = Clip.query.filter_by(
        clip_id=clip_id,
        user_id=current_user.id
    ).first_or_404()

    db.session.delete(clip)
    db.session.commit()
    return jsonify({'success': True})


@app.route('/api/settings', methods=['POST'])
@login_required
def api_save_settings():
    """Save user preferences from onboarding or settings page."""
    data = request.get_json()

    if 'twitch_username' in data:
        current_user.twitch_username = data['twitch_username']
    if 'kick_username' in data:
        current_user.kick_username = data['kick_username']
    if 'clip_style' in data:
        current_user.clip_style = data['clip_style']
    if 'caption_style' in data:
        current_user.caption_style = data['caption_style']
    if 'tiktok_connected' in data:
        current_user.tiktok_connected = data['tiktok_connected']
    if 'youtube_connected' in data:
        current_user.youtube_connected = data['youtube_connected']

    db.session.commit()
    return jsonify({'success': True})


# ============================================================
#  STARTUP
# ============================================================

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
        print("✅ Database ready.")
        print("✅ PogClip server starting...")
        print("   Open http://localhost:5000 in your browser")
    app.run(debug=True, port=5000)
